JOSM/buildings_tools: update to JOSM 8863 - fixes NoSuchMethodError - fixes #josm11972
git-svn-id: https://svn.openstreetmap.org/applications/editors/josm@31641 b9d5c4c9-76e1-0310-9c85-f3177eceb1e4